# Generated by Django 4.1.3 on 2022-12-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0002_salesorders_date_salesorders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorders',
            name='products',
            field=models.ManyToManyField(to='products.products'),
        ),
    ]
